Build templates for AI Builder Mod.
Each template describes a structure the AI can build.
Templates focus on dimensions, materials, and layout patterns.

TEMPLATES = {
    "small_starter_house" {
        "name": "Small Starter House",
        "description": "A cozy 5x5 oak starter home with a pitched roof, door, and windows.",
        "dimensions": "5 wide x 5 deep x 4 tall",
        "block_count": "~65 blocks",
        "materials": ["oak_planks", "oak_stairs", "glass_pane", "oak_door", "torch"],
        "instructions": [
            "Foundation: Fill a 5x5 area at y=0 with oak_planks",
            "Walls: 3-high oak_planks around the perimeter",
            "  - Leave (2, 0, 0) and (2, 1, 0) open for the door on the front face (z=0)",
            "  - Place glass_pane at (1, 1, 0), (3, 1, 0) on front",
            "  - Place glass_pane at (1, 1, 4), (3, 1, 4) on back",
            "  - Place glass_pane at (0, 1, 1), (0, 1, 3) on left side",
            "  - Place glass_pane at (4, 1, 1), (4, 1, 3) on right side",
            "Door: oak_door in the opening at (2, 0, 0) and (2, 1, 0)",
            "Roof: oak_stairs creating an A-frame",
            "  - At y=3: place oak_stairs along the ridge, rising toward center",
            "  - At y=4: single row of oak_stairs at x=2 along z-axis",
            "Interior: torch at (2, 1, 2)"
        ]
    },

    "medieval_house": {
        "name": "Medieval House",
        "description": "A sturdy 7x5 stone-and-timber medieval house with a steep roof.",
        "dimensions": "7 wide x 5 deep x 5 tall",
        "block_count": "~120 blocks",
        "materials": ["cobblestone", "oak_planks", "spruce_planks", "spruce_stairs", "glass_pane", "oak_door", "lantern", "spruce_fence"],
        "instructions": [
            "Foundation: Fill a 7x5 area with cobblestone at y=0",
            "Floor: spruce_planks on top of foundation",
            "Walls: 4-high using cobblestone with oak_log pillars at corners and midpoints",
            "  - Corner posts: oak_log at (0,1-3,0), (6,1-3,0), (0,1-3,4), (6,1-3,4)",
            "  - Wall fill between posts: cobblestone",
            "  - Front face (z=0): door at (3,0-1,0), glass_pane at (1,2,0) and (5,2,0)",
            "  - Back face (z=4): glass_pane at (1,1-2,4) and (5,1-2,4)",
            "  - Side faces: glass_pane at (0,1-2,2) and (6,1-2,2)",
            "Door: oak_door at (3,0,0) and (3,1,0)",
            "Above door: upside-down cobblestone_stairs at (3,3,0)",
            "Window trim: spruce_fence around glass_pane windows",
            "Roof: steep A-frame with spruce_stairs",
            "  - Base of roof at y=4, extending 1 block beyond walls (x from -1 to 7)",
            "  - Ridge at y=6 along x=3, z from -1 to 5",
            "  - Fill triangular ends at z=-1 and z=5 with spruce_planks",
            "  - roof overhangs: spruce_stairs at y=4 extending 1 block out",
            "Decor: lantern hanging from roof eaves at front",
            "Interior: torch at (3, 1, 2), crafting_table at (1, 1, 2)"
        ]
    },

    "watchtower": {
        "name": "Watchtower",
        "description": "A 5x5 stone watchtower, 8 blocks tall with arrow slits and a cone roof.",
        "dimensions": "5 wide x 5 deep x 10 tall",
        "block_count": "~150 blocks",
        "materials": ["stone_bricks", "cobblestone_stairs", "oak_fence", "lantern", "ladder"],
        "instructions": [
            "Base: 5x5 stone_bricks at y=0",
            "Floor: stone_bricks inside at y=0",
            "Walls: 8-high stone_bricks around the perimeter",
            "  - Arrow slits (1-block gaps in stone_bricks, replace with air):",
            "    - At y=2 on each face: (2,2,0), (0,2,2), (4,2,2), (2,2,4)",
            "    - At y=5 on each face: (2,5,0), (0,5,2), (4,5,2), (2,5,4)",
            "Floor level 2: stone_bricks slab at y=4 inside",
            "Floor level 3: stone_bricks slab at y=7 inside",
            "Top platform: stone_bricks at y=8",
            "Battlements: alternating stone_bricks and air gaps at y=9 on perimeter",
            "  - Place stone_bricks at corners: (0,9,0), (4,9,0), (0,9,4), (4,9,4)",
            "  - Place stone_bricks mid: (2,9,0), (0,9,2), (4,9,2), (2,9,4)",
            "Roof: cone-shaped with cobblestone_stairs above y=9 center",
            "  - 3x3 platform at y=10 centered at x=2,z=2",
            "  - 1x1 at y=11 centered at x=2,z=2",
            "Roof tip: oak_fence at (2,12,2) with lantern on top",
            "Interior: ladder from bottom to top along one wall",
            "Windows: glass_pane can be added behind arrow slits"
        ]
    },

    "castle": {
        "name": "Small Castle",
        "description": "A 19x15 castle with 4 corner towers, curtain walls, gatehouse, and central keep.",
        "dimensions": "19 wide x 15 deep x 12 tall",
        "block_count": "~800+ blocks",
        "materials": ["stone_bricks", "cobblestone", "cobblestone_stairs", "smooth_stone_slab", "oak_planks", "spruce_planks", "glass_pane", "iron_bars", "lantern"],
        "instructions": [
            "OUTER WALLS:",
            "  - Perimeter rectangle: 19x15, walls 4 blocks high",
            "  - Gates: 3-wide, 3-high opening on front (z=0) at x=8,9,10",
            "  - Wall walkway: stone_bricks slab on top of walls (y=4)",
            "  - Battlements: alternating stone_bricks and gaps at y=5 on outer edge",
            "",
            "CORNER TOWERS (4 total, at each corner):",
            "  - Base: 5x5 at each corner, overlapping walls",
            "  - Height: 8 blocks tall",
            "  - Arrow slits every 2 blocks",
            "  - Cone roof: cobblestone_stairs, narrowing from y=8 to y=11",
            "  - Flags: oak_fence with white_wool on top at y=12",
            "",
            "GATEHOUSE (front, z=0, x=6-12):",
            "  - Two towers flanking the gate, each 5x5, 8 tall",
            "  - Gate passage: 3-wide, cobblestone floor",
            "  - Portcullis: iron_bars across gate opening",
            "  - Guard room above gate at y=4: oak_planks floor, windows on front",
            "",
            "CENTRAL KEEP (center, x=4-14, z=3-11):",
            "  - Base: 11x9 cobblestone at y=0",
            "  - Walls: 5 blocks high, stone_bricks",
            "  - Entrance: oak_door at (9,0,3) and (9,1,3)",
            "  - Windows: glass_pane at y=2 and y=4 on all sides",
            "  - Roof: flat with battlements at y=5",
            "  - Interior: oak_planks floor, crafting table, furnace, bed at (9,1,7)",
            "",
            "COURTYARD (between gate and keep):",
            "  - Cobblestone path from gate to keep entrance",
            "  - Lanterns on fences along path",
            "",
            "MOAT (optional):",
            "  - 2-wide water channel around outer walls, 1 block deep",
            "  - Bridge across moat at gate entrance"
        ]
    },

    "modern_house": {
        "name": "Modern House",
        "description": "A sleek 7x7 modern house with clean lines, glass walls, and a flat roof.",
        "dimensions": "7 wide x 7 deep x 4 tall",
        "block_count": "~100 blocks",
        "materials": ["smooth_quartz", "white_concrete", "glass", "glass_pane", "spruce_planks", "spruce_door", "lantern", "white_carpet"],
        "instructions": [
            "Foundation: Fill 7x7 with smooth_quartz at y=0",
            "Walls: 3-high, mix of white_concrete and glass",
            "  - Front face (z=0):",
            "    - concrete at (0-1,1-3,0) and (5-6,1-3,0)",
            "    - glass from (2-4,1-3,0) for modern window wall",
            "    - door at (1,0-1,0) and (1,1-2,0) — spruce_door",
            "  - Back face (z=6): glass_pane from (1-5,1,6) at top",
            "  - Left side (x=0): mix of concrete and glass, glass at (0,1,2-4)",
            "  - Right side (x=6): solid white_concrete",
            "Windows: glass blocks (not panes) for clean modern look",
            "Roof: flat, spruce_planks at y=3",
            "  - Overhang: spruce_planks extending 1 block beyond walls",
            "  - Fence around roof edge: spruce_fence",
            "  - Lanterns at roof corners on fences",
            "Interior: white_carpet floor, torch at (3,1,3)",
            "Exterior: spruce_stairs as steps at front door"
        ]
    },

    "underwater_base": {
        "name": "Underwater Base",
        "description": "A 9x9 glass dome with airlock entrance, suitable for ocean floor.",
        "dimensions": "9 diameter x 5 tall",
        "block_count": "~200 blocks",
        "materials": ["glass", "prismarine", "sea_lantern", "spruce_planks", "spruce_door", "conduit", "lantern"],
        "instructions": [
            "Dome shape: hemisphere, 9x9 at base, layers above reduce by 1 each side",
            "Layer 0 (floor): 9x9 prismarine at y=0, inside is spruce_planks (7x7 center)",
            "Layer 1: 9x9 ring of glass (fill entire layer)",
            "  - Entrance: gap at (4,1,0) — 2 wide (x=3-5), 2 tall",
            "",

            "AIRLOCK TUNNEL (connects dome to outside):",
            "  - 2-wide, 2-high tunnel of glass from entrance extending 3 blocks outward",
            "  - First door at tunnel start (inside dome)",
            "  - Second door at tunnel end (outside)",
            "",
            "Layer 2: 7x7 ring of glass",
            "Layer 3: 5x5 ring of glass",
            "Layer 4: 3x3 glass ceiling",
            "Layer 5: 1x1 glass at top center",
            "",
            "Interior: spruce_planks floor at y=0, 5x5 area",
            "Lighting: sea_lantern at corners, lantern hanging from ceiling center",
            "Conduit: place at center (4,1,4) surrounded by prismarine frame",
            "Furniture: bed, crafting table, furnace, chests along walls"
        ]
    },

    "medieval_church": {
        "name": "Medieval Church",
        "description": "A 7x12 stone church with a tall nave, steeple roof, and stained glass.",
        "dimensions": "7 wide x 12 deep x 10 tall",
        "block_count": "~250 blocks",
        "materials": ["stone_bricks", "cobblestone", "dark_oak_planks", "glass_pane", "oak_door", "lantern"],
        "instructions": [
            "NAVE (main hall, front 7x8):",
            "  - Foundation: 7x8 cobblestone at y=0",
            "  - Walls: 6-high stone_bricks",
            "  - Front entrance (z=0): oak_door at (3,0-1,0), stone_bricks arch above",
            "  - Side windows: tall arched glass_pane windows at y=2-5",
            "    - Left (x=0): two windows at z=2 and z=5, each 1 wide, 3 tall",
            "    - Right (x=6): same as left",
            "  - Interior floor: dark_oak_planks",
            "",
            "CHANCEL (altar area, back 7x4):",
            "  - Raised 1 block (stone_bricks at y=1)",
            "  - Walls: same as nave, 6-high",
            "  - Large window at back wall (z=11): 3-wide, 4-high glass_pane",
            "  - Altar: enchantment_table or stairs at center back",
            "",
            "ROOF over Nave:",
            "  - Steep A-frame with stone_brick_stairs",
            "  - Base at y=6, ridge at y=8 along x=3",
            "  - Triangular end walls (z=0 and z=8) filled with stone_bricks",
            "",
            "ROOF over Chancel:",
            "  - Slightly lower A-frame, base at y=6, ridge at y=7",
            "",
            "STEEPLE (above front entrance):",
            "  - 3x3 tower from y=6 to y=9 at front (x=2-4, z=0-2)",
            "  - Spire from y=9 to y=12, narrowing to 1x1 at top",
            "  - Cross: oak_fence at top with iron_bars",
            "",
            "Interior: torches on pillars, lantern hanging from ceiling"
        ]
    },

    "lighthouse": {
        "name": "Lighthouse",
        "description": "A 5x5 red-and-white striped lighthouse, 14 blocks tall with beacon top.",
        "dimensions": "5 wide x 5 deep x 15 tall",
        "block_count": "~100 blocks",
        "materials": ["white_wool", "red_wool", "glass", "lantern", "sea_lantern", "iron_door", "ladder"],
        "instructions": [
            "Base: 5x5 stone_bricks at y=0",
            "Floor: stone_bricks inside at y=0",
            "Tower shaft: 5x5 ring, alternating red and white stripes every 2 blocks",
            "  - y=1-2: white_wool",
            "  - y=3-4: red_wool",
            "  - y=5-6: white_wool",
            "  - y=7-8: red_wool",
            "  - y=9-10: white_wool",
            "  - y=11-12: red_wool",
            "Door: iron_door at (2,0,0) and (2,1,0)",
            "Windows: glass at y=4, y=8, y=12 on each face (center of face)",
            "  - Place at (2,4,0), (0,4,2), (4,4,2), (2,4,4)",
            "  - Repeat at y=8 and y=12",
            "Top floor (y=13): 5x5 platform, floor of sea_lantern",
            "  - Glass walls (no roof) — lantern room",
            "Roof: cobblestone_stairs cone above y=13",
            "  - 3x3 at y=14, 1x1 at y=15",
            "Light: beacon or sea_lantern at (2,15,2)",
            "Interior: ladder up center from bottom to top"
        ]
    },

    "viking_longhouse": {
        "name": "Viking Longhouse",
        "description": "A 9x5 dark oak longhouse with a distinctive curved roof.",
        "dimensions": "9 wide x 5 deep x 5 tall",
        "block_count": "~100 blocks",
        "materials": ["dark_oak_planks", "dark_oak_log", "stripped_spruce_log", "cobblestone", "spruce_stairs", "lantern", "oak_door"],
        "instructions": [
            "Base: 9x5 cobblestone at y=0",
            "Floor: dark_oak_planks at y=1",
            "Walls: dark_oak_log posts at corners and every 3rd block, stripped_spruce_log in between",
            "  - Front face (z=0): door opening at (4,1-2,0)",
            "  - Walls are 3 blocks high (y=1 to y=3)",
            "  - Small windows: glass_pane at (1,2,0), (7,2,0), (4,2,4)",
            "",
            "Door: oak_door at (4,1,0) and (4,2,0)",
            "",
            "ROOF (distinctive curved longhouse style):",
            "  - Base at y=3, extends 1 block beyond walls on all sides",
            "  - Lower slope: spruce_stairs at y=3 from x=-1 to x=9, z=-1 to z=5",
            "  - Mid ridge: spruce_planks at y=4 from x=-1 to x=9 along z=1.5 to z=2.5",
            "  - Upper ridge: spruce_stairs at y=5 from x=0 to x=8",
            "  - End walls (triangular): fill with dark_oak_planks at x=-1 and x=9",
            "",
            "Smoke hole: gap in roof center at (4,5,2) with campfire below",
            "Interior: cobblestone furnace at (1,1,2), crafting table at (7,1,2)",
            "  - Beds along walls, torches on posts, lantern hanging from ridge beam"
        ]
    },

    "japanese_pagoda": {
        "name": "Japanese Pagoda",
        "description": "A 3-tier Japanese pagoda, 7x7 base with upward-curving roofs.",
        "dimensions": "7 wide x 7 deep x 12 tall",
        "block_count": "~200 blocks",
        "materials": ["cherry_planks", "cherry_log", "smooth_quartz", "red_wool", "lantern", "oak_fence", "bamboo"],
        "instructions": [
            "Base platform: 9x9 smooth_quartz at y=0, 1 block high",
            "",
            "TIER 1 (y=1 to y=4):",
            "  - Building: 7x7 cherry_planks floor at y=1",
            "  - Walls: 3-high cherry_log at corners, cherry_planks between",
            "  - Entrance: gap at (3,1-2,0) and (3,1-2,0)",
            "  - Door: oak_fence gate at entrance",
            "  - Roof: red_wool, extending to 9x9 at y=4",
            "  - Eaves curve up: red_wool slabs at outer edges",
            "",
            "TIER 2 (y=5 to y=7):",
            "  - Floor: 5x5 cherry_planks at y=5 centered",
            "  - Walls: 2-high cherry_log at corners, cherry_planks between",
            "  - Roof: red_wool extending to 7x7 at y=7, eaves curve up",
            "",
            "TIER 3 (y=8 to y=10):",
            "  - Floor: 3x3 cherry_planks at y=8 centered",
            "  - Walls: 2-high cherry_planks",
            "  - Roof: red_wool extending to 5x5 at y=10",
            "",
            "SPIRE (y=11 to y=14):",
            "  - oak_fence post at center (3,11-13,3)",
            "  - Lantern at top (3,14,3)",
            "",
            "Decor: bamboo plants at corners, lanterns hanging from each roof tier",
            "Path: stone_brick_path from entrance outward"
        ]
    },

    "iron_farm": {
        "name": "Iron Farm",
        "description": "A 10x8 iron golem farm using 3 villagers and a zombie. Produces iron ingots via golem spawning.",
        "dimensions": "10 wide x 8 deep x 6 tall",
        "block_count": "~200 blocks",
        "materials": ["stone", "oak_planks", "glass", "oak_fence", "ladder", "trapped_chest", "hopper", "water_bucket", "oak_door", "lantern", "piston", "redstone", "observer"],
        "instructions": [
            "LOCATION: Build 20+ blocks above ground or in the sky for best rates.",
            "",
            "PLATFORM: 10x8 stone at y=0, this is the spawning platform.",
            "  - Center 2x8 area: lava (covered with stone pressure plates for safety)",
            "",
            "VILLAGER POD (center of one long side at z=0):",
            "  - 3x3x3 enclosure of glass so villagers are visible but safe",
            "  - Inside: 3 villagers and 3 beds",
            "  - Name tagged villagers so they don't despawn",
            "  - Villagers need line of sight to zombie",
            "",
            "ZOMBIE PIT (directly in front of villager pod, same side):",
            "  - 1x2x2 hole with a named zombie inside",
            "  - Iron trapdoor on top so zombie can see villagers but not escape",
            "  - Water in pit to keep zombie bouncing (prevents drowning)",
            "",
            "GOLEM SPAWNING:",
            "  - Golems spawn on the 10x8 platform",
            "  - Surround platform with walls 2 high so golems don't escape",
            "  - Water streams push golems into a central collection point",
            "",
            "KILLING CHAMBER (below collection point):",
            "  - Lava blade or campfire for killing golems",
            "  - Hopper chain into trapped_chest for collection",
            "  - Ladder access for player to retrieve items",
            "",
            "ROOF: glass roof at y=5 to prevent other mob spawns while letting light in",
            "Lighting: lanterns inside villager pod and around exterior"
        ]
    },

    "piglin_barter_farm": {
        "name": "Piglin Barter Farm",
        "description": "A 7x7 nether-based gold farm with piglin bartering for gold, obsidian, and ender pearls.",
        "dimensions": "7 wide x 7 deep x 8 tall",
        "block_count": "~150 blocks",
        "materials": ["nether_bricks", "crimson_planks", "glass", "lantern", "hopper", "chest", "iron_bars", "ladder", "soul_torch"],
        "instructions": [
            "LOCATION: Build in the Nether (required for piglin spawning).",
            "",
            "PLATFORM: 7x7 nether_bricks at y=0, spawn platform.",
            "  - Build at y=30 or below for best piglin spawn rates.",
            "",
            "WALLS: 3-high nether_bricks around platform perimeter",
            "  - Leave 1-block gaps at ground level on all sides for piglins to walk in",
            "  - Top edge: overhang of nether_brick_fence to prevent piglins climbing out",
            "",
            "CEILING: nether_bricks at y=3, solid roof to block light",
            "  - This prevents other mob spawns and keeps the area dark",
            "",
            "BARTERING AREA (center):",
            "  - Player stands at center (3,1,3) at y=0",
            "  - Place gold ingots in player's offhand to trigger bartering",
            "  - Surround player with iron_bars at y=1-2 in a 3x3 ring for protection",
            "",
            "COLLECTION:",
            "  - Hopper ring around the player area feeding into a central chest",
            "  - Water streams along floor edges push items toward hoppers",
            "",
            "LIGHTING:",
            "  - soul_torch inside the farm to prevent other mob spawns",
            "  - No regular torches (piglins are neutral in any light)",
            "",
            "ACCESS: ladder from top entrance down to player position"
        ]
    },

    "mob_spawner_xp_farm": {
        "name": "Mob Spawner XP Farm",
        "description": "A 9x9 dungeon-based XP farm built around a monster spawner, with a 20-block drop chute.",
        "dimensions": "9 wide x 9 deep x 12 tall",
        "block_count": "~300 blocks",
        "materials": ["cobblestone", "glass", "water_bucket", "lantern", "ladder", "chest", "hopper"],
        "instructions": [
            "LOCATION: Find a dungeon with a monster spawner first.",
            "  - Dig a 9x9 room centered on the spawner, 3 blocks high initially.",
            "",
            "SPAWNER ROOM (y=0 to y=3):",
            "  - Clear 9x9 area with spawner at center (4,1,4)",
            "  - Light up with torches to stop spawning while building",
            "  - Place water source blocks along one wall (at y=1)",
            "  - Water flows across floor pushing mobs to opposite side",
            "  - Dig a 2x2 hole at the water collection point",
            "",
            "DROP CHUTE (from y=0 down to y=-10):",
            "  - 2x2 vertical shaft, 20 blocks deep",
            "  - Water at the bottom of the drop chute to break fall",
            "    (water source at y=-11, flows to y=-10 where mobs land)",
            "  - Mobs take falling damage but survive (1/2 heart remaining)",
            "",
            "KILLING ROOM (y=-10 to y=-8):",
            "  - 3x3 room at bottom of chute",
            "  - Player stands at eye level with mobs",
            "  - Punch/attack mobs through a 1-block gap (1HKO after fall)",
            "  - XP orbs fly to player through the gap",
            "",
            "COLLECTION:",
            "  - Hopper under killing floor feeding into chest",
            "  - Items from mob drops collected automatically",
            "",
            "ACCESS: ladder shaft from top to bottom along one wall",
            "LIGHTING: spawner room must be dark (torches only while building, then remove)"
        ]
    },

    "sugarcane_farm": {
        "name": "Automatic Sugarcane Farm",
        "description": "A 7x5 observer-based automatic sugarcane farm producing 100+ cane per hour.",
        "dimensions": "7 wide x 5 deep x 4 tall",
        "block_count": "~80 blocks",
        "materials": ["dirt", "glass", "piston", "observer", "redstone", "water_bucket", "chest", "hopper"],
        "instructions": [
            "BED: 7x5 area at y=0, dig 1 block deep trench along x=0 to x=6 at z=0",
            "  - Fill trench with water source blocks",
            "  - Place dirt blocks along the water edge (x=0 to x=6, z=1 to z=3)",
            "  - Plant sugarcane on dirt blocks (grows up to 3 blocks tall)",
            "",
            "OBSERVER/PISTON ARRAY (behind each sugarcane column):",
            "  - For each column at z=1, z=2, z=3:",
            "    - Place observer at (x, 2, z-1) facing the sugarcane",
            "    - Place piston at (x, 2, z-2) facing the sugarcane",
            "    - Redstone dust from observer to piston",
            "  - When sugarcane reaches 3 blocks, observer triggers piston",
            "  - Piston breaks the middle sugarcane (top drops as item)",
            "",
            "COLLECTION (behind pistons):",
            "  - Water channel at ground level behind pistons (z=-1, flowing to one end)",
            "  - Hopper and chest at channel end",
            "",
            "WALLS: glass on all sides to prevent items flying out",
            "ROOF: optional, glass roof to let sunlight in",
            "LIGHTING: not needed (sugarcane grows with sunlight)"
        ]
    },

    "villager_trading_hall": {
        "name": "Villager Trading Hall",
        "description": "A 11x9 trading hall with 12 villager stalls for easy trading access.",
        "dimensions": "11 wide x 9 deep x 5 tall",
        "block_count": "~250 blocks",
        "materials": ["oak_planks", "glass", "oak_fence", "lantern", "oak_door", "cobblestone", "ladder", "bell"],
        "instructions": [
            "FLOOR: 11x9 oak_planks at y=0",
            "  - Build on flat ground or raise above ground level",
            "",
            "VILLAGER STALLS (6 on each long side, total 12):",
            "  - Each stall: 2 wide x 3 deep x 3 high",
            "  - Front: oak_fence gate as door (player interacts through it)",
            "  - Back wall: solid oak_planks",
            "  - Floor: cobblestone slab inside stall",
            "  - Each stall has a bed inside (behind the villager)",
            "  - Workstation block in each stall matching desired trade",
            "",
            "STALL LAYOUT (left side x=0, z=2-8):",
            "  - Stall 1: (0-1, 0-2, 2-4) — bed at back, workstation",
            "  - Stall 2: (0-1, 0-2, 5-7) — bed at back, workstation",
            "",
            "STALL LAYOUT (right side x=9-10, z=2-8):",
            "  - Stall 3: (9-10, 0-2, 2-4)",
            "  - Stall 4: (9-10, 0-2, 5-7)",
            "",
            "More pairs along the x-axis...",
            "",
            "WALKING AISLE (center, x=2-8, z=0-8):",
            "  - 7-wide open space for the player to walk",
            "  - Bell at center ceiling (4,4,4) to summon villagers",
            "",
            "LIGHTING: lanterns every 5 blocks along ceiling",
            "ROOF: oak_planks at y=4 to keep villagers safe from weather",
            "",
            "ACCESS: oak_door entrance at (5,0,8) and (5,1,8) on front side",
            "PATH: stone_brick_path leading to entrance"
        ]
    },

    "enderman_xp_farm": {
        "name": "Enderman XP Farm",
        "description": "An End-based enderman farm built on a small end island with a 42-block drop.",
        "dimensions": "15 wide x 15 deep x 10 tall",
        "block_count": "~400 blocks",
        "materials": ["end_stone", "oak_planks", "oak_trapdoor", "water_bucket", "hopper", "chest", "ladder", "ender_pearl"],
        "instructions": [
            "LOCATION: Build in The End, on a small end island far from the main island.",
            "  - Bring building materials through the end portal.",
            "",
            "PLATFORM: 15x15 end_stone at y=0, 30+ blocks above the island surface.",
            "  - Build high up so endermen spawn only on your platform.",
            "",
            "SPAWN PLATFORM: 15x15 area with 2.5 block ceiling",
            "  - Place oak_trapdoors on floor at 2-block intervals",
            "  - Endermen see trapdoors as 'open' and fall into them",
            "  - 2 blocks of air above floor, then solid ceiling",
            "",
            "DROP CHUTE (center):",
            "  - 3x3 hole at center of platform",
            "  - 40 blocks deep (from y=0 to y=-40)",
            "  - Water at bottom to break fall (endermen survive with 1/2 heart)",
            "",
            "KILLING ROOM (y=-40):",
            "  - 5x5 room with 3-block ceiling",
            "  - Player stands at y=-39, swings at endermen at y=-40",
            "  - 1-hit kill after 40-block fall",
            "  - XP orbs fly toward player",
            "",
            "COLLECTION:",
            "  - Hopper line from killing room floor to chest",
            "  - Collects ender pearls and other drops",
            "",
            "ACCESS: ender_pearl to teleport up to spawn platform, or build ladder",
            "LIGHTING: no torches needed (endermen only spawn in dark)"
        ]
    },

    "automatic_tree_farm": {
        "name": "Automatic Tree Farm",
        "description": "A 9x5 automatic tree farm using observers and pistons. Harvests oak/birch trees.",
        "dimensions": "9 wide x 5 deep x 8 tall",
        "block_count": "~120 blocks",
        "materials": ["dirt", "piston", "observer", "redstone", "glass", "bone_meal", "dropper", "chest", "hopper"],
        "instructions": [
            "BED: 9x5 area at y=0",
            "  - Fill with dirt blocks in a 3x3 grid at center (x=3-5, z=1-3)",
            "  - These are the tree planting spots",
            "",
            "GROWTH CHAMBER:",
            "  - Glass walls, 7 blocks tall to accommodate tree growth",
            "  - Roof at y=7 with 3x3 hole at center for tree top clearance",
            "",
            "BONE MEAL DISPENSER (above each sapling):",
            "  - Dropper at (x, 6, z) above each sapling position, facing down",
            "  - Fill droppers with bone_meal",
            "  - Redstone clock to trigger droppers every few seconds",
            "",
            "HARVEST SYSTEM:",
            "  - Observer wall along one side (x=2, z=1-3, y=1-6) detecting tree growth",
            "  - Pistons at y=1 behind observers, push when tree grows",
            "  - Top piston at y=5 to break higher logs",
            "",
            "COLLECTION:",
            "  - Water channel at base along x=1",
            "  - Hopper and chest at end of channel",
            "  - Saplings, apples, and wood float into collection",
            "",
            "PLANTING: place oak or birch saplings on dirt blocks manually",
            "ACCESS: door at front, glass walls to view growth"
        ]
    },
}
